name: cnn_libras
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - absl-py=0.7.1=py37_0
  - astor=0.7.1=py_0
  - binutils_impl_linux-64=2.31.1=h6176602_1
  - binutils_linux-64=2.31.1=h6176602_3
  - bzip2=1.0.6=h14c3975_1002
  - c-ares=1.15.0=h14c3975_1001
  - ca-certificates=2019.1.23=0
  - cairo=1.14.12=h8948797_3
  - certifi=2019.3.9=py37_0
  - cycler=0.10.0=py_1
  - dbus=1.13.6=h746ee38_0
  - expat=2.2.6=he6710b0_0
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.13.0=h9420a91_0
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.10.0=he983fc9_0
  - fribidi=1.0.5=h7b6447c_0
  - gast=0.2.2=py_0
  - gcc_impl_linux-64=7.3.0=habb00fd_1
  - gcc_linux-64=7.3.0=h553295d_3
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.56.2=hd408876_0
  - graphite2=1.3.13=h23475e2_0
  - graphviz=2.40.1=h21bd128_2
  - grpcio=1.16.1=py37hf8bcb03_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - gxx_impl_linux-64=7.3.0=hdf63c60_1
  - gxx_linux-64=7.3.0=h553295d_3
  - h5py=2.8.0=py37h989c5e5_3
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - icu=58.2=hf484d3e_1000
  - jasper=2.0.14=h07fcdf6_1
  - jpeg=9c=h14c3975_1001
  - keras=2.2.4=py37_1
  - keras-applications=1.0.7=py_1
  - keras-preprocessing=1.0.9=py_1
  - kiwisolver=1.1.0=py37hc9558a2_0
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1
  - libgpuarray=0.7.6=h14c3975_1003
  - libiconv=1.15=h516909a_1005
  - libopenblas=0.3.3=h5a2b251_3
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3=h7b6447c_0
  - libpng=1.6.37=hed695b0_0
  - libprotobuf=3.7.1=h8b12597_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.10=h2733197_2
  - libuuid=1.0.3=h1bed415_2
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=h13577e0_0
  - mako=1.0.7=py_1
  - markdown=2.6.11=py_0
  - markupsafe=1.1.1=py37h14c3975_0
  - matplotlib=3.0.3=py37_1
  - matplotlib-base=3.0.3=py37h5f35d83_1
  - mock=3.0.4=py37_0
  - ncurses=6.1=hf484d3e_1002
  - numpy=1.16.3=py37he5ce36f_0
  - openssl=1.1.1=h7b6447c_0
  - pango=1.42.4=h049681c_0
  - pcre=8.43=he6710b0_0
  - pip=19.1=py37_0
  - pixman=0.38.0=h7b6447c_0
  - protobuf=3.7.1=py37he1b5a44_0
  - pthread-stubs=0.4=h14c3975_1001
  - pydot=1.4.1=py37_0
  - pygpu=0.7.6=py37h3010b51_1000
  - pyparsing=2.4.0=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - python=3.7.3=h5b0a415_0
  - python-dateutil=2.8.0=py_0
  - pyyaml=5.1=py37h14c3975_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=hf8c457e_1001
  - scikit-learn=0.20.3=py37h22eb022_0
  - scipy=1.2.1=py37h09a28d5_1
  - setuptools=41.0.1=py37_0
  - sip=4.19.8=py37hf484d3e_1000
  - six=1.12.0=py37_1000
  - sqlite=3.26.0=h67949de_1001
  - tensorboard=1.13.1=py37_0
  - tensorflow=1.13.1=py37_0
  - tensorflow-estimator=1.13.0=py_0
  - termcolor=1.1.0=py_2
  - theano=1.0.4=py37hf484d3e_1000
  - tk=8.6.9=h84994c4_1001
  - tornado=6.0.2=py37h516909a_0
  - werkzeug=0.15.2=py_0
  - wheel=0.33.1=py37_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xz=5.2.4=h14c3975_1001
  - yaml=0.1.7=h14c3975_1001
  - zlib=1.2.11=h14c3975_1004
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - opencv-python==4.1.0.25
prefix: /home/lucaaslb/anaconda3/envs/sem_gpu

